### ISSUE TITLE
Question around xlr-xldeploy-plugin usage

### ISSUE THREAD

**Issue by clumsyhands** [xebialabs-community/xlr-xldeploy-plugin#101]
Hi,

I was hoping someone can clarify something for me. We’ve recently upgraded our XLR version from 7.x to 8.5.x. 

We’ve always used both the official XLD plugin and this community edition and, since the upgrade, can see many XLD duplicate tasks available. Looking at the .jar files, both plugins contain the same tasks so that make sense. However, I’m curious to know whether we’ve been using the plugins wrong – was the community plugin designed to replace the official one? 

The way we have been using it is by running them side-by-side with each other.

Thanks

**Comment by jpflug** [comment]
Hello, actually the intention is the other way around: the official plugin is meant to replace the community version of the plugin. The benefit of the official plugin is that the work is tracked by our integration team dedicated to working on these types of plugins. We encourage you to leverage the official plugin as much as possible and submit feature requests to https://support.xebialabs.com/hc/en-us/requests/new if you need additional functionality from the community plugin missing in the official version. 

Hope this information is helpful,
Justin
