### ISSUE TITLE
UnicodeEncodeError when parsing the xml data for tasks

### ISSUE THREAD

**Issue by bmoussaud** [xebialabs-community/xlr-xldeploy-plugin#16]
need to encode('utf-8','ignore') http://stackoverflow.com/questions/1652904/unicodeencodeerror-ascii-codec-cant-encode-character?rq=1 
improvement : new property to display or not the step logs...

**Comment by bmoussaud** [comment]
see #18 for a quick workaround

**Comment by jdewinne** [comment]
Hi Benoit,

Do you mean when parsing the `xml` using `ET`. Like [here](https://github.com/xebialabs-community/xlr-xldeploy-plugin/blob/master/src/main/resources/xldeploy/XLDeployClient.py#L54)?

Regards,
Joris

**Comment by jdewinne** [comment]
Closing.
