### ISSUE TITLE
Get Latest Deployed Version throwing exception

### ISSUE THREAD

**Issue by bbonn** [xebialabs-community/xlr-xldeploy-plugin#17]
I am running the same setup with the 2.1.2 version of the plugin I have working with the 2.0.2 version and I am getting this error.   Let me know if you need more info.   I may get a chance to run more tests end of week.  Thanks!

Exception during execution:
TypeError: get_ci() takes exactly 3 arguments (4 given) in <script> at line number 11

**Comment by jdewinne** [comment]
Hi,

Are you aware that version 2.1.3 is already released? And if you're not able to upgrade to 2.1.3, can you send the full stacktrace? I'm thinking you might have some customization open in your `ext` folder.

Regards,
Joris

**Comment by MvdLinden** [comment]
Hi Joris,
seems that this problem is caused in XLDeployClient.py. Some calls to the get_ci method pass 3 params instead of 2. 'self"  should not be passed.

**Comment by jdewinne** [comment]
Thanks. Just release 2.1.5 which should fix this.
