### ISSUE TITLE
when creating CI you have to put a space in xml description

### ISSUE THREAD

**Issue by ltutar** [xebialabs-community/xlr-xldeploy-plugin#20]
Hi,

When trying to create a CI, you have to put a space in xml description and then save it. Otherwise, it will not work.
When CI ID and Ci Type is chosen, I do not want to touch the XML Descriptor.
See the attachment for the page.
![image001](https://cloud.githubusercontent.com/assets/7237078/16504264/62e09b7e-3f17-11e6-979e-9275e590b0e0.png)

We are using version XLR 5.0.0 and XLD 5.5.1.

**Comment by jdewinne** [comment]
I just checked this on the master branch and this works as expected. Also the Xml Descriptor isn't required anymore.
