### ISSUE TITLE
I already defined by XLD server. Why again?

### ISSUE THREAD

**Issue by ltutar** [xebialabs-community/xlr-xldeploy-plugin#22]
Is it possible that the XLD plug-in reuses the information of XLD definition. 
We have to define it again. It is confusing and error-prone. See the screenshots please.
![grabberraster 0179](https://cloud.githubusercontent.com/assets/7237078/16585513/8e76c10c-42c1-11e6-975e-917507f9b42c.jpg)
![grabberraster 0180](https://cloud.githubusercontent.com/assets/7237078/16585517/911f519e-42c1-11e6-9baa-fa4d4d0b63a8.jpg)

**Comment by jdewinne** [comment]
I would rather keep it the current way, so that all 3rd party tool configurations are in one place. So for XLR, XL Deploy is just another 3rd party config.
