### ISSUE TITLE
Setting Polling interval on Deploy Task lower than default (10) causes failure

### ISSUE THREAD

**Issue by grobert1** [xebialabs-community/xlr-xldeploy-plugin#23]
User reduced Polling interval on Deploy Task to 2, which caused a failure because it created a state that is not accounted for in deploytask.py code - the taskStates get skipped (DONE, EXECUTED, FAILED, STOPPED) and it jumps to sys.exit(1). Restoring polling to 10 gets us around the issue.

**Comment by jdewinne** [comment]
Hi,

Sorry for the late reply. The task states that are being tracked are defined in the [XLDeployClient.py](https://github.com/xebialabs-community/xlr-xldeploy-plugin/blob/master/src/main/resources/xldeploy/XLDeployClient.py#L123). What is the task state you get back?

Regards,
Joris

**Comment by jdewinne** [comment]
Closing because inactivity. Feel free to open another issue if this is still an issue.
