### ISSUE TITLE
Migrate Task does not Fail when it fails

### ISSUE THREAD

**Issue by bbonn** [xebialabs-community/xlr-xldeploy-plugin#25]
Version 2.1.5

We had 2 failures today, one was access denied bad password, an another where the package already exists.  Both legit errors but the Migrate task did not fail it juts moved on.   

Have not looked at the code yet, just wanted to get this logged.

**Comment by jdewinne** [comment]
Hi,

I would expect this is already fixed in the latest version. At least according to the source code.

Regards,
Joris

**Comment by jdewinne** [comment]
Can this be closed. Also the latest version v2.5.0 is not using the deprecated fetch api anymore.

**Comment by bbonn** [comment]
Sure let's close it.   I will grab the latest release and do some more testing.  Thanks Joris!
