### ISSUE TITLE
Undeploy Fails on 404 (Unavailable)

### ISSUE THREAD

**Issue by istairbn** [xebialabs-community/xlr-xldeploy-plugin#30]
If I try and undeploy a package that isn't present, we get a 404 error and the task fails. On the one hand, that's correct, the task has not taken action. However, the environment state is correct. Should there be an option to "accept not found" as a success? So that if it's not deployed, I don't have to skip/pass the task, but it should just continue to the next step?

**Comment by jdewinne** [comment]
That is indeed correct behavior. Would it help if we add for example a task like `does ci exist` and returns `True` or `False` in an output variable?

**Comment by istairbn** [comment]
Something like that would be useful. Even more useful if you could implement it at the start of a deployment task as a precondition.

**Comment by jdewinne** [comment]
I think if the output is `True` or `False` you could store that into an XLR variable, and reuse that in the next deployment/undeployment task in the precondition.

**Comment by jdewinne** [comment]
Released v2.6.0 with an additional task to check if a CI exists.

**Comment by jdewinne** [comment]
Closing issue. See v2.6.0
