### ISSUE TITLE
There is no Get CI task

### ISSUE THREAD

**Issue by MarkRx** [xebialabs-community/xlr-xldeploy-plugin#36]
The plugin contains a "create CI" and a "delete CI" task. There is no corresponding "get CI" task. Hence, XLR scripts are not able to perform logic based on knowledge of CI metadata.

**Comment by istairbn** [comment]
Are you looking to retrieve the CI XML so that you can manipulate it and then use it to recreate a similar one?

**Comment by MarkRx** [comment]
That is an option. In this particular case though I am looking to find out what deployeds used as placeholders when they were deployed.

**Comment by jdewinne** [comment]
That sounds like a very specific use case. Maybe it would be better to use a XLD CLI script for that, instead of adding a new type for it in the plugin?

**Comment by istairbn** [comment]
See latest pull request. Our original requirement was to check dictionary elements and confirm that they matched specific criteria. Easiest way to achieve it was to grab the source XML/JSON

**Comment by jdewinne** [comment]
This is now available in v3.3.0
