### ISSUE TITLE
Cryptic error message when an Environment does not exist

### ISSUE THREAD

**Issue by MarkRx** [xebialabs-community/xlr-xldeploy-plugin#41]
Suppose the following environment is passed in but does not exist:

Environments/sandbox/openshift/sandbox-routing

XLR will give the following error:

> 2017-01-25 15:22:17.105 [pool-1-thread-1] {task=Applications/Release5589468/Phase7034986/Task7012573} WARN  c.x.xlrelease.script.ScriptService - Exception during execution
> javax.script.ScriptException: Exception: Failed to prepare deployeds. Server return [500], with content [ : only whitespace content allowed before start tag and not E (position: START_DOCUMENT seen E... &#64;1:1)
> only whitespace content allowed before start tag and not E (position: START_DOCUMENT seen E... &#64;1:1) ] in <script> at line number 22
>         at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31) ~[jython-standalone-2.7.0.jar:na]
>         at com.xebialabs.xlrelease.script.ScriptExecutor.lambda$evalScriptPrivileged$53(ScriptExecutor.java:91) ~[server-4.8.1.jar:na]
>         at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_101]
>         at com.xebialabs.xlrelease.script.ScriptExecutor.evalScriptPrivileged(ScriptExecutor.java:90) ~[server-4.8.1.jar:na]
>         at com.xebialabs.xlrelease.script.ScriptExecutor.evalScriptWithUtilities(ScriptExecutor.java:84) ~[server-4.8.1.jar:na]
>         at com.xebialabs.xlrelease.script.ScriptExecutor.evalScriptWithApi(ScriptExecutor.java:73) ~[server-4.8.1.jar:na]
>         at com.xebialabs.xlrelease.script.ScriptService.executeScript(ScriptService.java:637) ~[REL-3352-hotfix.jar:na]
>         at com.xebialabs.xlrelease.script.ScriptService.lambda$executeCustomScriptTask$55(ScriptService.java:206) ~[REL-3352-hotfix.jar:na]
>         at com.xebialabs.deployit.plumbing.scheduler.Scheduler$1.run(Scheduler.java:84) ~[server-4.8.1.jar:na]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_101]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_101]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_101]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_101]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
>         at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
> Caused by: org.python.core.PyException: null
>         at org.python.core.PyException.doRaise(PyException.java:226) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.Py.makeException(Py.java:1337) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.Py.makeException(Py.java:1341) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.Py.makeException(Py.java:1345) ~[jython-standalone-2.7.0.jar:na]
>         at xldeploy.XLDeployClient$py.deployment_prepare_deployeds$20(__pyclasspath__/xldeploy/XLDeployClient.py:217) ~[na:na]
>         at xldeploy.XLDeployClient$py.call_function(__pyclasspath__/xldeploy/XLDeployClient.py) ~[na:na]
>         at org.python.core.PyTableCode.call(PyTableCode.java:167) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.PyBaseCode.call(PyBaseCode.java:307) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.PyBaseCode.call(PyBaseCode.java:198) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.PyFunction.__call__(PyFunction.java:482) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.PyMethod.__call__(PyMethod.java:228) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.PyMethod.__call__(PyMethod.java:218) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.pycode._pyx18.f$0(<script>:63) ~[na:na]
>         at org.python.pycode._pyx18.call_function(<script>) ~[na:na]
>         at org.python.core.PyTableCode.call(PyTableCode.java:167) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.PyCode.call(PyCode.java:18) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.Py.runCode(Py.java:1386) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.__builtin__.eval(__builtin__.java:497) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.core.__builtin__.eval(__builtin__.java:501) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259) ~[jython-standalone-2.7.0.jar:na]
>         at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:40) ~[jython-standalone-2.7.0.jar:na]
>         ... 16 common frames omitted

This happens because in deployment_prepare_deployeds the passed in deployment variable (which comes from deployment_prepare_initial) is:

> Environments/sandbox/openshift/sandbox-routing is not a Environment

This appears to be the raw response from XLD. There should be a better error handling when the response of deployment_prepare_undeploy, deployment_prepare_update, and deployment_prepare_initial is an error instead of an XML.

**Comment by jdewinne** [comment]
Thanks for reporting. The problem is actually even before the `deployment_prepare_deployeds`. So I've fixed that in [v2.8.4](https://github.com/xebialabs-community/xlr-xldeploy-plugin/releases/tag/v2.8.4).
