### ISSUE TITLE
Control Task Doesn't seem to work with parameters

### ISSUE THREAD

**Issue by bbonn** [xebialabs-community/xlr-xldeploy-plugin#47]
Hi there,

I am having trouble launching a control task with parameters via the built in task.   I have 2 parameters defined in the synthetic of my type in xld.   I tried passing as a dictionary in the task in the parameters field: 
{'webInstances': 1, 'queueInstances': 1}, but got this Exception during execution:
TypeError: cannot serialize 1 (type int) in <script> at line number 14.    Do I have to change the kind in the synth?   I have another control task where the values for the parameters are all defaulted in the synth but I couldn't get that to work either.  In that case I didn't put anything in the parameters field in the XLR task and it failed with  Exception during execution: SyntaxError: no viable alternative at input '<EOF>' in <unknown> at line number 21 at column number 11.

If this is not an issue, can you give me some advice on where my configuration is wrong.

Thanks I really appreciate any info!
Bernie

**Comment by bbonn** [comment]
Hi Again,

I think I understand what is going on better here.  So for the first problem I was trying to solve it appears you cannot just accept default values for parameters that are in the XLD control task synth entry.   I tried to leave the parameters field blank and have it use the defaults but it errors out in the add_parameter function at this line property_dict = dict(ast.literal_eval(parameters)) with the EOF error.   We use the default parameter because it is a password type value.   Anyway it would be cool if you could use the defaults if the field was empty.   
I also noticed that the same line errors out if you are using an Int which I am in another case.   Again I may have a work around which is actually just using the default string and account for that in the script, but wanted to bring it to you attention.   
Thanks!
Bernie

**Comment by jdewinne** [comment]
Thanks for pointing this out. I think this should be fixed now in [v2.8.8](https://github.com/xebialabs-community/xlr-xldeploy-plugin/releases/tag/v2.8.8)

**Comment by bbonn** [comment]
Hey Joris,

Not sure if you see posts on closed issues, but this we ran into this again although I think it is slightly different.   We have some control tasks that have parameters, but they are required=false and most times are empty.  This seems to break inside the prepare_control_task function, as it fails with:
`SyntaxError: no viable alternative at input '<EOF>'`
The prepared control task xml has this in it:

`<parameters>
<wls.Domain_checkwldepstatus id="parameters">
<deploymentsToCheck/>
</wls.Domain_checkwldepstatus>
</parameters>`

It seems it should ignore the parameters section if there are no values there.   Am I missing anything?

It works fine in XLD if you supply no parameters.

Thanks!
Bernie

**Comment by bbonn** [comment]
moved to new issue.
