### ISSUE TITLE
Duplication of Delete CI and Delete Infrastructure

### ISSUE THREAD

**Issue by istairbn** [xebialabs-community/xlr-xldeploy-plugin#55]
We now have Delete CI and Delete Infrastructure. 
Delete CI just amends the XL Deploy Repository. 
Delete Infrastructure removes all Deployables - essentially reverting all XLD Changes on the hardware. 

I like the principle behind this second task (even though I can't merge the changes into my repo!) as it makes sure it cleans up after itself. 

However, it does mean we have two Delete tasks with very discrete differences which will not be apparent to everyone - which is always risky. Do we think we should:

1. Keep the two actions completely separate (Repository / Underlying objects) - in which case we need to make sure the label and description of the task is spot on. Perhaps rename Delete CI to Delete CI from Repository?

2. Keep one task type "Delete CI" but improve it so that it can perform in the same way as Delete Infrastructure (i.e. clean up after itself). We could then offer a boolean for "Delete from Repository Only" to maintain the same compatibility that we currently have.

**Comment by erasmussen39** [comment]
I do agree that having a singular delete (with optional checkbox for dependencies) is valuable. Delete Infrastructure was created for a specific customer use case to remove Infrastructure and clean dependencies. For example, if you try to delete infrastructure with Delete CI and it still has dependencies, the task completes as if it succeeded, but it actually is failing under the covers (current Delete CI implementation isn't checking response). I agree that working towards a completely generic Delete CI with optional dependency handling should be the ultimate goal.

**Comment by istairbn** [comment]
:) that's why I've submitted my patch to Delete CI with ThrowOnFail - to at least stop false positives. 

It was added a while ago my end but my branch is so different to the master it won't merge anymore!

**Comment by jdewinne** [comment]
I've updated delete CI with error handling.
