### ISSUE TITLE
Control Task Doesn't handle empty parameters

### ISSUE THREAD

**Issue by bbonn** [xebialabs-community/xlr-xldeploy-plugin#69]
Hey There,

 We have some control tasks that have parameters, but they are required=false and most times are empty.  This seems to break inside the prepare_control_task function, as it fails with:
`SyntaxError: no viable alternative at input '<EOF>'`
The prepared control task xml has this in it:

`<parameters>
<wls.Domain_checkwldepstatus id="parameters">
<deploymentsToCheck/>
</wls.Domain_checkwldepstatus>
</parameters>`

It seems it should ignore the parameters section if there are no values there.   Am I missing anything?

It works fine in XLD if you supply no parameters.

Thanks!
Bernie

**Comment by bbonn** [comment]
Hello there,

Just FYI , we realized that if you include a key with no value in the parameters field that the task works.

`{'deploymentsToCheck': ''} `

 So we have a valid workaround for this.

Thanks,
Bernie

**Comment by jdewinne** [comment]
See v3.4.1
