### ISSUE TITLE
Select Server CI

### ISSUE THREAD

**Issue by steffo** [xebialabs-community/xlr-xldeploy-plugin#7]
When adding a task "Latest Version"  or "Deploy" the dropdown box for selecting the Server CI is empty.
XLR 4.7.1
xlr-xldeploy-plugin 1.1.5

**Comment by jdewinne** [comment]
Did you define/create an XLD server under `Settings - Configuration`?

**Comment by steffo** [comment]
Yes, I have multiple xld servers defined and they are being used in releases

**Comment by steffo** [comment]
Oke, I read your reply too fast. 
I had already defined XLD servers, under Settings->XLD servers. But I need to redefine them under Settings->Configuration. Thanks!
