### ISSUE TITLE
7.0.2 Issue with XLD 6.0.2

### ISSUE THREAD

**Issue by kmcallorum** [xebialabs-community/xlr-xldeploy-plugin#78]
Appears that deployment goes through looking at deployment report in XLD but the last entry is 

Display the step logs Exception during execution: Traceback (most recent call last): File "<script>", line 48, in <module> File "pyclasspath/xlr_xldeploy/XLDeployClient.py", line 441, in display_step_logs File "/app_1/xlr-7.0.2/lib/jython-standalone-2.7.0.jar/Lib/xml/etree/ElementTree.py", line 1303, in XML File "/app_1/xlr-7.0.2/lib/jython-standalone-2.7.0.jar/Lib/xml/etree/ElementTree.py", line 1656, in close File "/app_1/xlr-7.0.2/lib/jython-standalone-2.7.0.jar/Lib/xml/etree/ElementTree.py", line 1508, in _raiseerror File "<string>", line None xml.etree.ElementTree.ParseError: Character reference "&#x1b" is an invalid XML character.

**Comment by jdewinne** [comment]
Do you mean the following configuration:
+ XL Release 7.0.2
+ XL Deploy 6.0.2
+ Plugin version: ?
+ Executing a [deployTask](https://github.com/xebialabs-community/xlr-xldeploy-plugin/blob/master/src/main/resources/synthetic.xml#L41) with `displayStepLogs` set to `true`?

**Comment by kmcallorum** [comment]
Plugin version is the latest. What I found is joss restart script had an escape sequence into to print a line bold. Now this has worked all along but somehow the xml generated from xld on restart is streamed into xml now and without checking produces invalid xml. So I was able to workaround as the restart can perform as a corn and output to logs instead of console so for now that's the answer to the latest issue. But line 441 is the error in the plugin because xml is just be out in bad

**Comment by jdewinne** [comment]
Could it be that the restart script is producing some xml invalid characters? Is it possible to take that out of the restart script?
[line 441](https://github.com/xebialabs-community/xlr-xldeploy-plugin/blob/master/src/main/resources/xlr_xldeploy/XLDeployClient.py#L441) is just parsing the received xml. So this means the received xml from XL Deploy contains invalid characters, which I think should be fixed in the restart script or in XL Deploy.

**Comment by kmcallorum** [comment]
Could we possibly error handle this. Log where error came from and why it's error?

**Comment by jdewinne** [comment]
I think it's clear where the error is coming from, not? The plugin receives invalid xml. So this should be fixed in the restart script, or in XL Deploy.

**Comment by kmcallorum** [comment]
It took a while to find the error. Since this has the capability of doing try catch handling why not put it there and say error on blank instead of letting it fail
